<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yd.proto

namespace GPBMetadata;

class Yd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a340a0879642e70726f746f12027964221c0a046461746112090a017918" .
            "012001280912090a0164180220012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

