<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yd.proto

namespace Yd;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yd.data</code>
 */
class data extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string y = 1;</code>
     */
    private $y = '';
    /**
     * Generated from protobuf field <code>string d = 2;</code>
     */
    private $d = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $y
     *     @type string $d
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yd::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string y = 1;</code>
     * @return string
     */
    public function getY()
    {
        return $this->y;
    }

    /**
     * Generated from protobuf field <code>string y = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setY($var)
    {
        GPBUtil::checkString($var, True);
        $this->y = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string d = 2;</code>
     * @return string
     */
    public function getD()
    {
        return $this->d;
    }

    /**
     * Generated from protobuf field <code>string d = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setD($var)
    {
        GPBUtil::checkString($var, True);
        $this->d = $var;

        return $this;
    }

}

